### PR TITLE
OCR accuracy tool for screen_data

### PR DESCRIPTION
**Pull request by vmdocua**
Implement OCR accuracy tool to measure "noisseur" processed screen data in numbers. 

Main goal is to get statistics about trained data accuracy and post-processing accuracy. 

Polish project structure to correspond recommended patterns in con/* projects (pre-commit hooks, codespell, github workflows etc).

### CODE REVIEW

**Comment by yarikoptic** [comment]
so what is a sample output "in numbers"?

**Comment by vmdocua** [comment]
output in "numbers" something like listed below, so we can compare different models and ocr engines:

python tools/screen_data_accuracy.py
Images count: 5
[0]: patient-registration-001.png
    accuracy=80.73%, strict_match=69.56%, time=2.739 sec
[1]: patient-registration-002.png
    accuracy=61.33%, strict_match=47.82%, time=5.226 sec
[2]: patient-registration-003.png
    accuracy=89.34%, strict_match=82.6%, time=3.306 sec
[3]: patient-registration-004.png
    accuracy=87.32%, strict_match=78.26%, time=3.491 sec
[4]: patient-registration-005.png
    accuracy=85.32%, strict_match=78.26%, time=4.386 sec
--------------------------------------
Total screen count   : 5
Total time           : 19.148 sec
Average accuracy     : 80.81%
Average strict_match : 71.30%
Average time         : 3.830 sec
--------------------------------------
Done.

**Comment by yarikoptic** [comment]
so it compares images and not target text?

**Comment by vmdocua** [comment]
It provides final metrics/benchmarks for con/noisseur service results. Say "data/screen_data" folder contains reference images and expected screen data JSON model output. Tool pass images to con/noisseur instance REST API, get screen data JSON response back and compares this with reference values (these values created manually by human from real sreenshot pictures). Result is combination of OCR+postprocessing and regression if any. But it describes real quality of this system and what it should do. Ideal system/limit should return 100% accuracy, 100% match and 0ms processing time.

In practice it can be used to compare different trained data for tesseract right now, to find the best trained data, understand progress and next direction in trainings. Also it can be used to compare with other systems like EasyOCR or brothers (but these systems should be integrated first with con/noisseur).

Another usage case for this code is plain tests, unit tests, integration tests, to see and monitor con/noisseur service status  during project lifetime.

**Pull request merged**
